### ISSUE TITLE
Failure to get github.com/drone/drone-go/plugin

### ISSUE THREAD

**Issue by gonitely** [drone/drone-go#28]
go get "github.com/drone/drone-go/plugin"

**Comment by bradrydzewski** [comment]
that package was removed in preparation for the upcoming release, in which it has been deprecated. If you need that package please clone the following commit https://github.com/drone/drone-go/tree/eaa41f7836a191224ec5702d2458db07882ec269

**Comment by tboerger** [comment]
Look at the release/0.4 branches of the plugins, they are pinned and vendored to the last valid commit

**Comment by gabrielkwok** [comment]
ok thanks
